global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'elixir-cqrs'
    static_configs:
      - targets:
        - 'host.docker.internal:4000'  # Client Service
        # Command Service と Query Service は PubSub を使用するため、外部ポートなし