apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: elixir-cqrs-dev

nameSuffix: -dev

commonLabels:
  environment: development

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: elixir-cqrs-config
    behavior: merge
    literals:
      - MIX_ENV=dev
      - PHX_HOST=localhost
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=development

secretGenerator:
  - name: elixir-cqrs-secrets
    behavior: merge
    literals:
      - DATABASE_PASSWORD=postgres
      - SECRET_KEY_BASE=dev-secret-key-base-64-characters-long
      - ENCRYPTION_KEY=dev-encryption-key-32-characters

images:
  - name: IMAGE_PLACEHOLDER
    newName: ghcr.io/your-org/elixir-cqrs
    newTag: dev-latest