apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service
  namespace: elixir-cqrs-prod
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: client-service
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-service
  namespace: elixir-cqrs-prod
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: command-service
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-service
  namespace: elixir-cqrs-prod
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: query-service
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"