apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: elixir-cqrs

commonLabels:
  environment: production

patchesStrategicMerge:
  - deployment-patch.yaml
  - hpa.yaml

configMapGenerator:
  - name: elixir-cqrs-config
    behavior: merge
    literals:
      - MIX_ENV=prod
      - POOL_SIZE=20
      - PHX_HOST=elixir-cqrs.example.com
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=production

images:
  - name: IMAGE_PLACEHOLDER
    newName: ghcr.io/your-org/elixir-cqrs
    newTag: v1.0.0