apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elixir-cqrs-prod

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patches.yaml

configMapGenerator:
  - name: app-config
    literals:
      - MIX_ENV=prod
      - LOG_LEVEL=info

secretGenerator:
  - name: app-secrets
    literals:
      - secret-key-base=your-production-secret-key-base
  - name: database-secrets
    literals:
      - command-db-url=ecto://user:pass@postgres:5432/command_prod
      - query-db-url=ecto://user:pass@postgres:5432/query_prod
      - event-db-url=ecto://user:pass@postgres:5432/event_prod

images:
  - name: ghcr.io/elixir-cqrs/client-service
    newTag: v1.0.0
  - name: ghcr.io/elixir-cqrs/command-service
    newTag: v1.0.0
  - name: ghcr.io/elixir-cqrs/query-service
    newTag: v1.0.0

replicas:
  - name: client-service
    count: 3
  - name: command-service
    count: 3
  - name: query-service
    count: 5