apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elixir-cqrs

resources:
  - namespace.yaml
  - client-service.yaml
  - command-service.yaml
  - query-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: elixir-cqrs

images:
  - name: ghcr.io/elixir-cqrs/client-service
    newTag: latest
  - name: ghcr.io/elixir-cqrs/command-service
    newTag: latest
  - name: ghcr.io/elixir-cqrs/query-service
    newTag: latest