apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elixir-cqrs

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-deployment.yaml
  - client-service-deployment.yaml
  - command-service-deployment.yaml
  - query-service-deployment.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: elixir-cqrs