# Sealed Secrets を使用したシークレット管理の例
# 
# Sealed Secrets のインストール:
# kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.24.0/controller.yaml
#
# kubeseal CLI のインストール:
# brew install kubeseal
#
# シークレットの暗号化:
# kubectl create secret generic elixir-cqrs-secrets \
#   --from-literal=DATABASE_PASSWORD=your-password \
#   --from-literal=SECRET_KEY_BASE=your-key \
#   --dry-run=client -o yaml | \
#   kubeseal -o yaml > sealed-secret.yaml

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: elixir-cqrs-secrets
  namespace: elixir-cqrs
spec:
  encryptedData:
    DATABASE_USER: # encrypted value here
    DATABASE_PASSWORD: # encrypted value here
    SECRET_KEY_BASE: # encrypted value here
    ENCRYPTION_KEY: # encrypted value here
  template:
    metadata:
      name: elixir-cqrs-secrets
      namespace: elixir-cqrs
    type: Opaque