apiVersion: v1
kind: Secret
metadata:
  name: elixir-cqrs-secrets
  namespace: elixir-cqrs
  labels:
    app.kubernetes.io/name: elixir-cqrs
type: Opaque
stringData:
  # データベース認証情報
  DATABASE_USER: "postgres"
  DATABASE_PASSWORD: "changeme" # 実環境では変更してください
  DATABASE_URL: "postgres://postgres:changeme@postgres-service:5432/event_store"
  
  # Phoenix 秘密鍵
  SECRET_KEY_BASE: "changeme-64-character-secret-key-base" # 実環境では変更してください
  
  # 暗号化キー
  ENCRYPTION_KEY: "changeme-32-character-encryption-key" # 実環境では変更してください